version: '2'

services:

  postgres:
    container_name: 
      "postgres"
    image: "postgres:9.6-alpine"
    restart: 
      "always"
    env_file:
        - .env

  kuttadmin:
      container_name: kuttadmin
      image: registry.gitlab.com/ugleiton/kutt-admin:latest
      restart: always
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on: 
        - postgres
      command: tail -f /dev/null
