version: '2'

services:

  kuttadmin:
    container_name: kuttadmin
    image: registry.gitlab.com/ugleiton/kutt-admin:latest
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASEKUTT_HOST=${DATABASEKUTT_HOST}
      - POSTGRESKUTT_DB=${POSTGRESKUTT_DB}
      - POSTGRESKUTT_USER=${POSTGRESKUTT_USER}
      - POSTGRESKUTT_PASSWORD=${POSTGRESKUTT_PASSWORD}
      - SITE_TITLE=${SITE_TITLE}
    ports:
      - "8000:8000"
      

networks:
  escoteirosrs_gateway-network:
    external: true
